import { trpc } from "@/lib/trpc";
import { ArrowLeft, ExternalLink, Info, MapPin, Scale, Users } from "lucide-react";
import { Link, useRoute } from "wouter";

function money(value: number) { return `₹${new Intl.NumberFormat("en-IN", { notation: "compact", maximumFractionDigits: 2 }).format(value)}`; }

export default function AllocationCase() {
  const [, params] = useRoute("/allocation/:id");
  const scoreId = Number(params?.id);
  const detail = trpc.allocation.case.useQuery({ scoreId }, { enabled: Number.isFinite(scoreId) });
  if (detail.isLoading) return <div className="mx-auto max-w-[1260px] p-8 text-sm text-slate-500">Loading allocation context…</div>;
  if (detail.error || !detail.data) return <div className="mx-auto max-w-[1260px] rounded-2xl border border-rose-200 bg-rose-50 p-8 text-rose-800">This allocation context record could not be loaded.</div>;
  const caseData = detail.data;
  const direction = caseData.appliedVariancePercent > 0 ? "above" : caseData.appliedVariancePercent < 0 ? "below" : "at";
  return <div className="mx-auto max-w-[1260px] space-y-6"><Link href="/allocation" className="inline-flex items-center gap-2 text-sm font-semibold text-[#1d5d8c] hover:text-[#153f61]"><ArrowLeft className="h-4 w-4" />Back to allocation context</Link><section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="grid gap-6 bg-gradient-to-br from-[#112f4c] to-[#194d73] p-7 text-white md:grid-cols-[1fr_285px]"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-amber-300">Official allocation context record</p><h1 className="mt-3 font-display text-3xl font-semibold">{caseData.record.constituency}</h1><p className="mt-2 flex items-center gap-1.5 text-sm text-sky-100"><MapPin className="h-4 w-4" />{caseData.record.state} · {caseData.record.mpName}</p><p className="mt-5 max-w-2xl text-sm leading-6 text-sky-100/85">The allocation is <strong>{Math.abs(caseData.appliedVariancePercent).toFixed(1)}% {direction} the applicable peer median</strong>. This is statistical context from a public allocation export, not a finding of fault or fraud.</p></div><div className="rounded-2xl border border-white/10 bg-white/[0.08] p-5"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-amber-200">Allocation</p><p className="mt-2 font-display text-4xl font-semibold">{money(caseData.record.allocatedAmount)}</p><p className="mt-5 text-xs text-sky-100/75">Model score</p><p className="font-display text-2xl font-semibold">{caseData.modelScore}/100</p></div></div><div className="grid divide-y divide-slate-100 sm:grid-cols-3 sm:divide-x sm:divide-y-0"><Fact label="State peer median" value={money(caseData.statePeerMedian)} /><Fact label="National peer median" value={money(caseData.nationalPeerMedian)} /><Fact label="State comparison set" value={`${caseData.statePeerCount} records`} /></div></section>
    <section className="grid gap-6 lg:grid-cols-[1fr_340px]"><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-2"><Scale className="h-4 w-4 text-[#1d5d8c]" /><h2 className="font-semibold text-slate-900">What the trained model used</h2></div><div className="mt-5 divide-y divide-slate-100"><Evidence label="Observed public allocation" value={money(caseData.record.allocatedAmount)} description="Allocated amount recorded in the public MPLADS dashboard export." /><Evidence label="Peer baseline" value={money(caseData.statePeerMedian)} description="Median allocation for comparable records in the same state; national median is used only for smaller state groups." /><Evidence label="Applied variance" value={`${caseData.appliedVariancePercent > 0 ? "+" : ""}${caseData.appliedVariancePercent.toFixed(2)}%`} description="Percentage distance from the model’s selected peer baseline." /><Evidence label="Interpretation" value={caseData.contextBand.replaceAll("_", " ")} description="Context category only. It does not mean a high allocation is improper." /></div></div><aside className="space-y-4"><div className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><div className="flex items-center gap-2 text-sm font-semibold text-amber-900"><Info className="h-4 w-4" />Use with care</div><p className="mt-2 text-sm leading-6 text-amber-900/80">Public records do not include project outcomes, vendors, invoices, or investigation labels. The model cannot predict fraud and should not be used to rank people.</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#1d5d8c]">Source provenance</p><p className="mt-3 font-mono text-xs text-slate-700">{caseData.model.modelCode}</p><p className="mt-1 text-xs text-slate-500">{caseData.model.modelVersion}</p><a href={caseData.source.sourceUrl} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-1 text-xs font-semibold text-[#1d5d8c] hover:underline">Official MPLADS dashboard <ExternalLink className="h-3.5 w-3.5" /></a></div></aside></section>
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center gap-2 border-b border-slate-100 px-5 py-4"><Users className="h-4 w-4 text-[#1d5d8c]" /><div><h2 className="font-semibold text-slate-900">State peer context</h2><p className="mt-1 text-xs text-slate-500">Public allocation records used in this state comparison group.</p></div></div><div className="overflow-x-auto"><table className="min-w-full text-left"><thead className="bg-slate-50 text-[11px] font-semibold uppercase tracking-[0.1em] text-slate-500"><tr><th scope="col" className="px-5 py-3">Constituency</th><th scope="col" className="px-5 py-3">Public allocation</th><th scope="col" className="px-5 py-3 text-right">Peer variance</th></tr></thead><tbody className="divide-y divide-slate-100">{caseData.statePeers.map(peer => <tr key={peer.id}><td className="px-5 py-3"><p className="font-medium text-slate-800">{peer.constituency}</p><p className="mt-0.5 text-xs text-slate-500">{peer.mpName}</p></td><td className="px-5 py-3 text-sm text-slate-700">{money(peer.allocatedAmount)}</td><td className="px-5 py-3 text-right text-sm font-medium text-slate-700">{peer.appliedVariancePercent > 0 ? "+" : ""}{peer.appliedVariancePercent.toFixed(1)}%</td></tr>)}</tbody></table></div></section>
  </div>;
}

function Fact({ label, value }: { label: string; value: string }) { return <div className="p-5"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 font-semibold text-slate-900">{value}</p></div>; }
function Evidence({ label, value, description }: { label: string; value: string; description: string }) { return <div className="grid gap-2 py-4 sm:grid-cols-[1fr_auto]"><div><p className="font-medium text-slate-800">{label}</p><p className="mt-1 text-sm leading-6 text-slate-500">{description}</p></div><p className="font-display text-lg font-semibold capitalize text-slate-900">{value}</p></div>; }
