import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, ArrowUpRight, BrainCircuit, Database, ExternalLink, Info, MapPin, RefreshCw } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "wouter";

const bands = {
  high_variance: { label: "High variance", className: "border-amber-200 bg-amber-50 text-amber-800" },
  moderate_variance: { label: "Moderate variance", className: "border-sky-200 bg-sky-50 text-sky-800" },
  expected_range: { label: "Expected range", className: "border-slate-200 bg-slate-50 text-slate-600" },
} as const;

function money(value: number) { return `₹${new Intl.NumberFormat("en-IN", { notation: "compact", maximumFractionDigits: 2 }).format(value)}`; }

export default function AllocationContext() {
  const [band, setBand] = useState("all");
  const { user } = useAuth();
  const dashboard = trpc.allocation.dashboard.useQuery();
  const utils = trpc.useUtils();
  const retrain = trpc.allocation.retrain.useMutation({ onSuccess: () => utils.allocation.dashboard.invalidate() });
  const visible = useMemo(() => dashboard.data?.records.filter(item => band === "all" || item.contextBand === band) ?? [], [dashboard.data?.records, band]);

  if (dashboard.isLoading) return <div className="mx-auto max-w-[1440px] p-8 text-sm text-slate-500">Loading official allocation context…</div>;
  if (dashboard.error || !dashboard.data) return <div className="mx-auto max-w-[1440px] rounded-2xl border border-rose-200 bg-rose-50 p-8 text-rose-800"><p className="font-semibold">The allocation-context model could not load.</p><p className="mt-1 text-sm">{dashboard.error?.message ?? "No model response was returned."}</p></div>;
  const { model, source, kpis, bandBreakdown } = dashboard.data;

  return <div className="mx-auto max-w-[1440px] space-y-6"><section className="overflow-hidden rounded-3xl bg-[#102f4c] px-6 py-7 text-white shadow-xl shadow-slate-900/10 md:px-8"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-start"><div className="max-w-3xl"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-amber-300">Official source · trained context model</p><h1 className="mt-3 font-display text-3xl font-semibold leading-tight md:text-4xl">Allocation variance deserves context, not conclusions.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-sky-100/85">This trained peer-median model profiles the public MPLADS allocation export by state. It identifies records that differ from comparable allocations; it does not assess individuals, prove irregularity, or classify fraud.</p></div><div className="min-w-[230px] rounded-2xl border border-white/10 bg-white/[0.07] p-4"><div className="flex items-center gap-2 text-xs font-semibold text-amber-200"><BrainCircuit className="h-4 w-4" /> Model provenance</div><p className="mt-3 font-mono text-xs text-white">{model.modelCode}</p><p className="mt-1 text-xs text-sky-100/70">{model.modelVersion} · {model.trainingRows} public records</p>{user?.role === "admin" && <Button size="sm" onClick={() => retrain.mutate()} disabled={retrain.isPending} className="mt-4 h-8 rounded-lg bg-amber-300 text-xs text-[#102f4c] hover:bg-amber-200"><RefreshCw className={`mr-1.5 h-3.5 w-3.5 ${retrain.isPending ? "animate-spin" : ""}`} />Verify model source</Button>}</div></div></section>

    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Public records modelled" value={kpis.recordCount.toLocaleString("en-IN")} detail={`${kpis.stateCount} states / UTs`} icon={<Database className="h-4 w-4" />} /><Metric label="High variance context" value={kpis.highVarianceCount.toString()} detail="Requires explanation, not escalation" icon={<AlertTriangle className="h-4 w-4" />} /><Metric label="National peer median" value={money(kpis.medianAllocation)} detail="Allocation baseline" icon={<ArrowUpRight className="h-4 w-4" />} /><Metric label="Model scope" value="Context" detail="No verified outcome labels" icon={<Info className="h-4 w-4" />} /></section>

    <section className="grid gap-6 lg:grid-cols-[1fr_310px]"><div className="overflow-hidden rounded-2xl border border-slate-200/80 bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 px-5 py-4"><div><p className="font-semibold text-slate-900">Allocation context register</p><p className="mt-1 text-xs text-slate-500">Sorted by absolute difference from the relevant peer median.</p></div><Select value={band} onValueChange={setBand}><SelectTrigger aria-label="Filter allocation records by variance band" className="h-9 w-[190px] rounded-lg border-slate-200 text-xs"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All variance bands</SelectItem><SelectItem value="high_variance">High variance</SelectItem><SelectItem value="moderate_variance">Moderate variance</SelectItem><SelectItem value="expected_range">Expected range</SelectItem></SelectContent></Select></div><div className="overflow-x-auto"><table className="min-w-full text-left"><thead className="bg-slate-50 text-[11px] font-semibold uppercase tracking-[0.11em] text-slate-500"><tr><th scope="col" className="px-5 py-3">Context band</th><th scope="col" className="px-5 py-3">Constituency</th><th scope="col" className="px-5 py-3">Allocated amount</th><th scope="col" className="px-5 py-3">Peer context</th><th scope="col" className="px-5 py-3 text-right">Variance</th></tr></thead><tbody className="divide-y divide-slate-100">{visible.map(item => { const bandStyle = bands[item.contextBand]; return <tr key={item.id} className="transition hover:bg-sky-50/40"><td className="px-5 py-4"><span className={`inline-flex rounded-full border px-2.5 py-1 text-[11px] font-semibold ${bandStyle.className}`}>{bandStyle.label}</span></td><td className="px-5 py-4"><Link href={`/allocation/${item.id}`} className="group block"><p className="font-medium text-slate-900 group-hover:text-[#1d5d8c]">{item.record.constituency}</p><p className="mt-1 flex items-center gap-1 text-xs text-slate-500"><MapPin className="h-3 w-3" />{item.record.state} · {item.record.mpName}</p></Link></td><td className="px-5 py-4 text-sm font-medium text-slate-800">{money(item.record.allocatedAmount)}</td><td className="px-5 py-4 text-sm text-slate-600">{item.statePeerCount} state peers · median {money(item.statePeerMedian)}</td><td className="px-5 py-4 text-right"><span className="font-display text-xl font-semibold text-slate-900">{item.appliedVariancePercent > 0 ? "+" : ""}{item.appliedVariancePercent.toFixed(1)}%</span><p className="mt-1 text-[10px] uppercase tracking-wide text-slate-400">{item.varianceDirection.replaceAll("_", " ")}</p></td></tr>})}</tbody></table></div></div>
      <aside className="space-y-4"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-semibold uppercase tracking-[0.15em] text-[#1d5d8c]">Model distribution</p><div className="mt-4 space-y-3">{bandBreakdown.map(item => <div key={item.band}><div className="flex items-center justify-between text-sm"><span className="text-slate-700">{bands[item.band].label}</span><span className="font-semibold text-slate-900">{item.count}</span></div><div className="mt-1.5 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#1d5d8c]" style={{ width: `${(item.count / kpis.recordCount) * 100}%` }} /></div></div>)}</div></div><div className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><div className="flex items-center gap-2 text-sm font-semibold text-amber-900"><Info className="h-4 w-4" />Interpretation guardrail</div><p className="mt-2 text-sm leading-6 text-amber-900/80">A high-variance allocation can reflect valid administrative circumstances. Use it only to request context; never present it as evidence of misconduct.</p><a href={source.sourceUrl} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-1 text-xs font-semibold text-[#1d5d8c] hover:underline">Official dashboard <ExternalLink className="h-3.5 w-3.5" /></a></div></aside></section>
  </div>;
}

function Metric({ label, value, detail, icon }: { label: string; value: string; detail: string; icon: React.ReactNode }) { return <div className="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-slate-500">{label}</p><span className="text-[#1d5d8c]">{icon}</span></div><p className="mt-3 font-display text-3xl font-semibold text-slate-950">{value}</p><p className="mt-2 text-xs text-slate-500">{detail}</p></div>; }
