import { useState } from "react";
import { Bar, BarChart, Cell, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { AlertTriangle, ArrowRight, BadgeIndianRupee, ClipboardCheck, FolderKanban, RefreshCcw, ShieldAlert, UsersRound } from "lucide-react";
import { Link } from "wouter";
import { trpc } from "@/lib/trpc";
import { compactMoney, dateLabel, riskLabel, riskTone, statusLabel, statusTone } from "@/lib/format";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";

const chartPalette = ["#dc5b45", "#d18a23", "#4a86b8", "#7d6fa9", "#678f76"];

function Metric({ label, value, caption, icon: Icon, tone }: { label: string; value: string | number; caption: string; icon: typeof FolderKanban; tone: string }) {
  return <div className="group rounded-2xl border border-slate-200/80 bg-white p-5 shadow-[0_8px_30px_rgba(15,40,65,0.05)] transition duration-200 hover:-translate-y-0.5 hover:shadow-[0_14px_36px_rgba(15,40,65,0.08)]"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.12em] text-slate-500">{label}</p><p className="mt-3 text-3xl font-semibold tracking-tight text-slate-950">{value}</p></div><div className={`grid h-10 w-10 place-items-center rounded-xl ${tone}`}><Icon className="h-5 w-5" /></div></div><p className="mt-3 text-xs leading-5 text-slate-500">{caption}</p></div>;
}

export default function Dashboard() {
  const [queueRisk, setQueueRisk] = useState("all");
  const dashboard = trpc.audit.dashboard.useQuery();
  const { user } = useAuth();
  const runAudit = trpc.audit.run.useMutation({ onSuccess: () => dashboard.refetch() });
  if (dashboard.isLoading) return <div className="grid gap-4 md:grid-cols-4">{Array.from({ length: 4 }).map((_, index) => <div key={index} className="h-40 animate-pulse rounded-2xl bg-slate-200/70" />)}</div>;
  if (dashboard.error || !dashboard.data) return <div className="rounded-2xl border border-rose-200 bg-rose-50 p-6 text-rose-800"><p className="font-semibold">The command centre could not load.</p><p className="mt-1 text-sm">{dashboard.error?.message ?? "Please refresh and try again."}</p></div>;
  const { kpis, riskBreakdown, alerts, latestRun } = dashboard.data;
  const visibleAlerts = queueRisk === "all" ? alerts : alerts.filter(item => item.riskType === queueRisk);
  return <div className="mx-auto max-w-[1440px] space-y-7">
    <section className="overflow-hidden rounded-[28px] bg-[#102b46] px-6 py-7 text-white shadow-[0_18px_55px_rgba(12,35,58,0.20)] md:px-9 md:py-8"><div className="relative z-10 flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div className="max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-amber-300">MPLAD risk command centre</p><h1 className="mt-3 font-display text-3xl font-semibold tracking-tight md:text-4xl">Focus field review where the evidence is strongest.</h1><p className="mt-3 max-w-xl text-sm leading-6 text-sky-100/80">Transparent signals for cost variance, potential duplicate work, vendor concentration, stalled delivery, and source-record quality.</p></div><div className="flex flex-wrap items-center gap-3"><div className="rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-xs text-sky-100"><p className="font-medium text-white">Latest analysis</p><p className="mt-1">{latestRun ? `${latestRun.runCode} · ${dateLabel(latestRun.completedAt)}` : "Preparing workspace"}</p></div>{user?.role === "admin" ? <button onClick={() => runAudit.mutate()} disabled={runAudit.isPending} className="inline-flex h-11 items-center gap-2 rounded-xl bg-amber-300 px-4 text-sm font-semibold text-[#102b46] transition hover:bg-amber-200 disabled:opacity-60"><RefreshCcw className={`h-4 w-4 ${runAudit.isPending ? "animate-spin" : ""}`} />{runAudit.isPending ? "Running analysis" : "Run audit"}</button> : <button onClick={() => startLogin()} className="inline-flex h-11 items-center gap-2 rounded-xl border border-white/15 bg-white/10 px-4 text-sm font-semibold text-white transition hover:bg-white/15"><ShieldAlert className="h-4 w-4" />Sign in to review</button>}</div></div><div className="pointer-events-none absolute -right-24 -top-24 h-72 w-72 rounded-full bg-sky-300/10 blur-3xl" /></section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Projects monitored" value={kpis.projectCount} caption={`${kpis.vendorCount} registered vendors in the workspace`} icon={FolderKanban} tone="bg-sky-50 text-sky-700" /><Metric label="Open priorities" value={kpis.openAlerts} caption="Cases awaiting analyst disposition" icon={ClipboardCheck} tone="bg-amber-50 text-amber-700" /><Metric label="Critical cases" value={kpis.criticalAlerts} caption="Highest-scoring open review priorities" icon={AlertTriangle} tone="bg-rose-50 text-rose-700" /><Metric label="Sanctioned value" value={compactMoney(kpis.valueAtRisk)} caption="Across currently open risk cases" icon={BadgeIndianRupee} tone="bg-violet-50 text-violet-700" /></section>
    <section className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><div className="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-base font-semibold text-slate-900">Risk signals by detector</p><p className="mt-1 text-xs text-slate-500">Open cases in the most recent completed audit run</p></div><UsersRound className="h-5 w-5 text-slate-400" /></div><div className="mt-5 h-[245px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={riskBreakdown} margin={{ top: 8, right: 8, left: -22, bottom: 0 }}><XAxis dataKey="type" tickFormatter={value => riskLabel[value] ?? value} tick={{ fontSize: 11, fill: "#64748b" }} axisLine={false} tickLine={false} /><YAxis allowDecimals={false} tick={{ fontSize: 11, fill: "#64748b" }} axisLine={false} tickLine={false} /><Tooltip cursor={{ fill: "#f8fafc" }} contentStyle={{ borderRadius: 12, border: "1px solid #e2e8f0", fontSize: 12 }} formatter={(value: number) => [value, "Open cases"]} labelFormatter={label => riskLabel[label] ?? label} /><Bar dataKey="count" radius={[8, 8, 2, 2]}>{riskBreakdown.map((item, index) => <Cell key={item.type} fill={chartPalette[index]!} />)}</Bar></BarChart></ResponsiveContainer></div></div>
      <div className="rounded-2xl border border-[#e5d9c4] bg-[#fffdf8] p-5 shadow-sm"><p className="text-xs font-semibold uppercase tracking-[0.15em] text-amber-800">Analyst standard</p><blockquote className="mt-4 font-display text-xl leading-8 text-[#2a3b4f]">“Prioritise verification. Preserve the evidence. Never treat a statistical signal as a conclusion.”</blockquote><div className="mt-6 grid grid-cols-3 gap-2 text-center"><div className="rounded-xl bg-white p-3"><p className="text-lg font-semibold text-[#18324c]">5</p><p className="mt-0.5 text-[10px] uppercase tracking-wider text-slate-500">Signal types</p></div><div className="rounded-xl bg-white p-3"><p className="text-lg font-semibold text-[#18324c]">100</p><p className="mt-0.5 text-[10px] uppercase tracking-wider text-slate-500">Max score</p></div><div className="rounded-xl bg-white p-3"><p className="text-lg font-semibold text-[#18324c]">1</p><p className="mt-0.5 text-[10px] uppercase tracking-wider text-slate-500">Evidence trail</p></div></div></div></section>
    <section className="rounded-2xl border border-slate-200/80 bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 px-5 py-4"><div><p className="text-base font-semibold text-slate-900">Priority alert queue</p><p className="mt-1 text-xs text-slate-500">Highest-scoring open and reviewable cases</p></div><div className="flex items-center gap-3"><select aria-label="Filter dashboard priority queue by signal type" value={queueRisk} onChange={event => setQueueRisk(event.target.value)} className="h-9 rounded-lg border border-slate-200 bg-white px-3 text-xs font-medium text-slate-700 outline-none focus:border-sky-500 focus:ring-2 focus:ring-sky-100"><option value="all">All signals</option>{Object.entries(riskLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><Link href="/alerts" className="inline-flex items-center gap-1 text-sm font-semibold text-[#1d5d8c] hover:text-[#164a71]">View full queue <ArrowRight className="h-4 w-4" /></Link></div></div><div className="overflow-x-auto"><table className="min-w-full text-left"><thead className="bg-slate-50/70 text-[11px] font-semibold uppercase tracking-[0.1em] text-slate-500"><tr><th scope="col" className="px-5 py-3">Priority</th><th scope="col" className="px-5 py-3">Project</th><th scope="col" className="px-5 py-3">Signal</th><th scope="col" className="px-5 py-3">Status</th><th scope="col" className="px-5 py-3 text-right">Score</th></tr></thead><tbody className="divide-y divide-slate-100">{visibleAlerts.length ? visibleAlerts.map(item => <tr key={item.id} className="transition hover:bg-sky-50/40"><td className="px-5 py-4"><span className={`inline-flex rounded-full border px-2.5 py-1 text-[11px] font-semibold ${riskTone[item.riskBand]}`}>{item.riskBand}</span></td><td className="px-5 py-4"><Link href={`/alerts/${item.id}`} className="block"><p className="font-medium text-slate-900 hover:text-[#1d5d8c]">{item.project.title}</p><p className="mt-1 text-xs text-slate-500">{item.project.projectCode} · {item.project.district}</p></Link></td><td className="px-5 py-4"><p className="text-sm text-slate-700">{riskLabel[item.riskType]}</p><p className="mt-1 max-w-[260px] truncate text-xs text-slate-500">{item.title}</p></td><td className="px-5 py-4"><span className={`inline-flex rounded-full border px-2.5 py-1 text-[11px] font-medium ${statusTone[item.alertStatus]}`}>{statusLabel[item.alertStatus]}</span></td><td className="px-5 py-4 text-right"><span className="font-display text-xl font-semibold text-slate-900">{item.riskScore}</span><span className="ml-1 text-xs text-slate-400">/100</span></td></tr>) : <tr><td colSpan={5} className="px-5 py-10 text-center text-sm text-slate-500">No priority case in this detector category. Use the full queue to explore all review states.</td></tr>}</tbody></table></div></section>
  </div>;
}
