import { useEffect, useState } from "react";
import { AlertTriangle, ArrowLeft, BarChart3, Database, MapPin, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import { AllocationDashboard, GuardianAlert, GuardianUser, guardianRequest, formatMoney, humanise } from "@/lib/guardianApi";
import { fetchOfficialAllocationCsv, officialAllocationFilename } from "@/lib/officialAllocation";
import { ErrorPanel, Loading, QuarkTableCard, QuarkWorkflowHeading } from "./FastApiViews";

type AlertCase = { case: GuardianAlert & { evidence: Record<string, unknown> }; project: Record<string, unknown>; provenance: Record<string, unknown>; review_history: { action: string; note: string; reviewer_id: number; created_at: string }[] };
type AllocationCase = { score: { id: number; context_band: string; model_score: number; state_peer_count: number; state_peer_median: number; applied_variance_percent: number }; record: { state: string; mp_name: string; constituency: string; allocated_amount: number }; model: { model_code: string; methodology: string }; source: { source_url: string }; state_peers: { record_id: number; mp_name: string; constituency: string; allocated_amount: number; model_score: number; applied_variance_percent: number }[] };

export function AlertCaseView({ id, token, user, onHydrate, setStatus }: { id: string; token: string; user: GuardianUser; onHydrate: () => Promise<void>; setStatus: (value: string) => void }) {
  const [item, setItem] = useState<AlertCase | null>(null); const [error, setError] = useState(""); const [note, setNote] = useState(""); const [busy, setBusy] = useState(false);
  const load = async () => { try { setItem(await guardianRequest<AlertCase>(`/alerts/${id}`, token)); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not load this alert case."); } };
  useEffect(() => { void load(); }, [id, token]);
  const review = async (action: "field_verification" | "dismissed" | "resolved") => { if (note.trim().length < 3) { setError("Add a review note of at least three characters."); return; } setBusy(true); try { await guardianRequest(`/alerts/${id}/review`, token, { method: "POST", body: JSON.stringify({ action, note }) }); setNote(""); await load(); await onHydrate(); setStatus("Review action recorded."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Review could not be recorded."); } finally { setBusy(false); } };
  if (error && !item) return <ErrorPanel text={error} />; if (!item) return <Loading text="Loading alert case…" />;
  return <div className="quark-case-screen"><Link href="/alerts" className="quark-case-back"><ArrowLeft />Back to alert queue</Link><QuarkWorkflowHeading label="Evidence-led review" title="Alert Case Review" text="Inspect the evidence payload, project context, and review history before recording a human decision." /><div className="quark-case-summary-grid"><section className="quark-case-evidence-card"><span className="quark-case-label">{humanise(item.case.risk_type)} · {item.case.risk_band}</span><h2>{item.case.title}</h2><p>{item.case.rationale}</p><div className="quark-evidence-panel"><strong>Evidence payload</strong><pre>{JSON.stringify(item.case.evidence, null, 2)}</pre></div></section><aside className="quark-case-context-card"><ShieldCheck /><span>Project Context</span><strong>{String(item.project.project_code)}</strong><p>{String(item.project.title)}</p><dl><div><dt>Audit run</dt><dd>{String(item.provenance.run_code)}</dd></div><div><dt>Algorithm</dt><dd>{String(item.provenance.algorithm_version)}</dd></div></dl></aside></div>{user.role !== "viewer" && <section className="quark-review-decision-card"><div><span>Human decision</span><h2>Record review action</h2><p>Document the decision and supporting context without altering the source audit evidence.</p></div><textarea value={note} onChange={event => setNote(event.target.value)} placeholder="Explain the review decision and evidence required…" /><div className="quark-review-actions"><button disabled={busy} onClick={() => review("field_verification")} className="quark-download-btn">Request field verification</button><button disabled={busy} onClick={() => review("resolved")} className="quark-view-all-btn">Resolve</button><button disabled={busy} onClick={() => review("dismissed")} className="quark-view-all-btn">Dismiss</button></div>{error && <p className="quark-form-error">{error}</p>}</section>}<section className="quark-history-card"><div className="quark-table-title"><div><h2>Review History</h2><p>Persisted reviewer actions for this alert case.</p></div></div>{item.review_history.length ? item.review_history.map((entry, index) => <div key={`${entry.created_at}-${index}`} className="quark-history-row"><strong>{humanise(entry.action)}</strong><p>{entry.note}</p><small>{new Date(entry.created_at).toLocaleString()}</small></div>) : <p className="quark-history-empty">No reviewer action has been recorded.</p>}</section></div>;
}

export function AllocationView({ token, user }: { token: string; user: GuardianUser }) {
  const [data, setData] = useState<AllocationDashboard | null>(null); const [file, setFile] = useState<File | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const load = async () => { try { setData(await guardianRequest<AllocationDashboard>("/allocations", token)); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not load official allocation context."); } };
  useEffect(() => { void load(); }, [token]);
  const importPackagedOfficialSource = async () => { setBusy(true); setError(""); try { const csv = await fetchOfficialAllocationCsv(); const body = new FormData(); body.append("file", new File([csv], officialAllocationFilename, { type: "text/csv" })); await guardianRequest("/allocations/import", token, { method: "POST", body }); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Official allocation import failed."); } finally { setBusy(false); } };
  const importSelectedOfficialSource = async () => { if (!file) return; setBusy(true); setError(""); try { const body = new FormData(); body.append("file", file); await guardianRequest("/allocations/import", token, { method: "POST", body }); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Official allocation import failed."); } finally { setBusy(false); } };
  if (!data) return <div className="quark-screen-stack"><QuarkWorkflowHeading label="Official public source" title="Allocation Context Dashboard" text="Import the packaged public MPLADS allocation export to create a versioned peer-context model." /><section className="quark-allocation-import-card"><span><Database /></span><div><h2>Official allocation context is not loaded</h2><p>{error || "The public allocation export creates explainable peer context only. It does not classify fraud or wrongdoing."}</p>{user.role === "admin" && <div className="quark-allocation-import-actions"><button onClick={importPackagedOfficialSource} disabled={busy} className="quark-download-btn">{busy ? "Importing official source…" : "Import packaged official allocation source"}</button><small>Uses the verified packaged public export, checksum, source scope, and retrieval time.</small><label className="quark-file-field"><span>Or upload an official allocated-limit CSV</span><input aria-label="Official allocation CSV" type="file" accept=".csv,text/csv" onChange={event => setFile(event.target.files?.[0] ?? null)} /></label><button onClick={importSelectedOfficialSource} disabled={!file || busy} className="quark-view-all-btn">Import selected official CSV</button><small>Expected fields: State, MP, Constituency, and Allocated Amount. Use this control for the file downloaded from the official dashboard.</small></div>}</div></section></div>;
  return <div className="quark-screen-stack"><QuarkWorkflowHeading label="Official source · peer-context model" title="Allocation Context Dashboard" text="Allocation variance deserves context, not conclusions. The model uses public source records and transparent peer comparisons." /><section className="quark-allocation-hero"><div><span>Current model</span><strong>{data.model.model_code}</strong><p>{data.model.methodology}</p></div><small>{data.source.row_count} public records · version {data.model.model_version}</small></section><div className="quark-allocation-kpis"><AllocationMetric icon={<Database />} label="Public Records" value={data.kpis.record_count} /><AllocationMetric icon={<MapPin />} label="States / UTs" value={data.kpis.state_count} /><AllocationMetric icon={<AlertTriangle />} label="High Variance" value={data.kpis.high_variance_count} /><AllocationMetric icon={<BarChart3 />} label="Median Allocation" value={formatMoney(data.kpis.median_allocation)} /></div><QuarkTableCard title="Allocation Context Register" text="Sorted by variance from a state peer median, with national fallback for smaller peer groups."><table className="quark-dashboard-table"><thead><tr><th>Band</th><th>Constituency</th><th>Amount</th><th>Peer Context</th><th>Variance</th></tr></thead><tbody>{data.records.map(row => <tr key={row.id}><td><span className={`quark-dashboard-risk ${row.context_band.toLowerCase()}`}>{humanise(row.context_band)}</span></td><td><Link href={`/allocation/${row.id}`} className="quark-allocation-link">{row.record.constituency}</Link><small className="quark-row-subtitle">{row.record.state} · {row.record.mp_name}</small></td><td>{formatMoney(row.record.allocated_amount)}</td><td>{row.state_peer_count} peers · {formatMoney(row.state_peer_median)}</td><td><strong>{row.applied_variance_percent > 0 ? "+" : ""}{row.applied_variance_percent.toFixed(1)}%</strong></td></tr>)}</tbody></table></QuarkTableCard></div>;
}

export function AllocationCaseView({ id, token }: { id: string; token: string }) { const [data, setData] = useState<AllocationCase | null>(null); const [error, setError] = useState(""); useEffect(() => { guardianRequest<AllocationCase>(`/allocations/${id}`, token).then(setData).catch(reason => setError(reason instanceof Error ? reason.message : "Could not load allocation case.")); }, [id, token]); if (error) return <ErrorPanel text={error} />; if (!data) return <Loading text="Loading allocation context…" />; return <div className="quark-case-screen"><Link href="/allocation" className="quark-case-back"><ArrowLeft />Back to allocation context</Link><QuarkWorkflowHeading label="Public allocation peer context" title={data.record.constituency} text={`${data.record.mp_name} · ${data.record.state}. Review variance with its peer group, source context, and documented limits.`} /><div className="quark-case-summary-grid"><section className="quark-allocation-details-card"><span className={`quark-dashboard-risk ${data.score.context_band.toLowerCase()}`}>{humanise(data.score.context_band)} · score {data.score.model_score}</span><div className="quark-allocation-detail-grid"><Info label="Allocated amount" value={formatMoney(data.record.allocated_amount)} /><Info label="Applied variance" value={`${data.score.applied_variance_percent > 0 ? "+" : ""}${data.score.applied_variance_percent.toFixed(1)}%`} /><Info label="State peer median" value={formatMoney(data.score.state_peer_median)} /><Info label="State peers" value={String(data.score.state_peer_count)} /></div></section><aside className="quark-interpretation-card"><AlertTriangle /><strong>Interpretation guardrail</strong><p>A high-variance public allocation can have legitimate administrative explanations. It is a request for context, never evidence of misconduct.</p><a href={data.source.source_url} target="_blank" rel="noreferrer">Open official dashboard</a></aside></div><QuarkTableCard title="State Peer Group" text="Records used for comparative context in the current model run."><table className="quark-dashboard-table"><thead><tr><th>MP</th><th>Constituency</th><th>Allocation</th><th>Variance</th></tr></thead><tbody>{data.state_peers.map(peer => <tr key={peer.record_id}><td>{peer.mp_name}</td><td>{peer.constituency}</td><td>{formatMoney(peer.allocated_amount)}</td><td>{peer.applied_variance_percent > 0 ? "+" : ""}{peer.applied_variance_percent.toFixed(1)}%</td></tr>)}</tbody></table></QuarkTableCard></div>; }

function AllocationMetric({ icon, label, value }: { icon: React.ReactNode; label: string; value: React.ReactNode }) { return <div className="quark-dashboard-stat-card blue"><span className="quark-dashboard-stat-icon">{icon}</span><div><p>{label}</p><strong>{value}</strong></div></div>; }
function Info({ label, value }: { label: string; value: string }) { return <div><dt>{label}</dt><dd>{value}</dd></div>; }
