import { useEffect, useState } from "react";
import { ShieldCheck, UserPlus, Users } from "lucide-react";
import { GuardianUser, guardianRequest, humanise } from "@/lib/guardianApi";
import { ErrorPanel, Loading, QuarkWorkflowHeading } from "./FastApiViews";

type ManagedUser = GuardianUser & { is_active: boolean; created_at: string };

export function TeamView({ token, user }: { token: string; user: GuardianUser }) {
  const [users, setUsers] = useState<ManagedUser[]>([]); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [role, setRole] = useState<"reviewer" | "viewer">("reviewer"); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const load = async () => { try { setUsers(await guardianRequest<ManagedUser[]>("/users", token)); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not load analyst accounts."); } };
  useEffect(() => { void load(); }, [token]);
  const create = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); try { await guardianRequest("/users", token, { method: "POST", body: JSON.stringify({ name, email, password, role }) }); setName(""); setEmail(""); setPassword(""); setRole("reviewer"); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not create analyst account."); } finally { setBusy(false); } };
  const update = async (managed: ManagedUser, updatePayload: Record<string, unknown>) => { setBusy(true); try { await guardianRequest(`/users/${managed.id}`, token, { method: "PATCH", body: JSON.stringify(updatePayload) }); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not update analyst account."); } finally { setBusy(false); } };
  if (user.role !== "admin") return <ErrorPanel text="Only administrators can manage analyst accounts." />;
  return <div className="quark-screen-stack"><QuarkWorkflowHeading label="Administrator control" title="Analyst Account Management" text="Create permitted reviewer and viewer accounts, maintain role boundaries, and deactivate access when it is no longer needed." /><div className="quark-analyst-management-grid"><form onSubmit={create} className="quark-analyst-form"><span className="quark-analyst-form-icon"><UserPlus /></span><h2>Add an analyst</h2><p>Create a reviewer or read-only viewer account. Share the temporary password through a secure channel only.</p><label>Full name<input required value={name} onChange={event => setName(event.target.value)} /></label><label>Email<input required type="email" value={email} onChange={event => setEmail(event.target.value)} /></label><label>Temporary password<input required type="password" minLength={12} value={password} onChange={event => setPassword(event.target.value)} /></label><label>Role<select value={role} onChange={event => setRole(event.target.value as "reviewer" | "viewer")}><option value="reviewer">Reviewer — inspect and review alerts</option><option value="viewer">Viewer — read-only access</option></select></label><button disabled={busy} className="quark-download-btn">{busy ? "Saving…" : "Create analyst account"}</button>{error && <p className="quark-form-error">{error}</p>}</form><section className="quark-analyst-directory"><div className="quark-table-title"><div><h2>Analyst Accounts</h2><p>Deactivate access when a user no longer needs the workspace. The active administrator session is protected.</p></div><Users /></div>{users.length ? <div className="quark-analyst-list">{users.map(managed => <article key={managed.id} className="quark-analyst-row"><div className="quark-analyst-identity"><span><ShieldCheck /></span><div><strong>{managed.name}</strong><p>{managed.email}</p><small>{humanise(managed.role)} · {managed.is_active ? "Active" : "Deactivated"}</small></div></div>{managed.id !== user.id && <div className="quark-analyst-actions"><select value={managed.role === "admin" ? "reviewer" : managed.role} disabled={managed.role === "admin" || busy} onChange={event => update(managed, { role: event.target.value })}><option value="reviewer">Reviewer</option><option value="viewer">Viewer</option></select><button disabled={busy || managed.role === "admin"} onClick={() => update(managed, { is_active: !managed.is_active })}>{managed.is_active ? "Deactivate" : "Reactivate"}</button></div>}</article>)}</div> : <Loading text="Loading analyst accounts…" />}</section></div></div>;
}
