"""Initial FastAPI PostgreSQL schema.

Revision ID: 0001_guardian
Revises:
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0001_guardian"
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    op.create_table("users", sa.Column("id", sa.Integer, primary_key=True), sa.Column("email", sa.String(320), nullable=False, unique=True), sa.Column("name", sa.String(255), nullable=False), sa.Column("password_hash", sa.String(255), nullable=False), sa.Column("role", sa.String(24), nullable=False, server_default="viewer"), sa.Column("is_active", sa.Boolean, nullable=False, server_default=sa.true()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("vendors", sa.Column("id", sa.Integer, primary_key=True), sa.Column("vendor_code", sa.String(72), nullable=False, unique=True), sa.Column("name", sa.String(255), nullable=False), sa.Column("state", sa.String(128), nullable=False))
    op.create_table("projects", sa.Column("id", sa.Integer, primary_key=True), sa.Column("project_code", sa.String(72), nullable=False, unique=True), sa.Column("title", sa.String(255), nullable=False), sa.Column("description", sa.Text), sa.Column("category", sa.String(128), nullable=False), sa.Column("state", sa.String(128), nullable=False), sa.Column("district", sa.String(128), nullable=False), sa.Column("locality", sa.String(160), nullable=False), sa.Column("vendor_id", sa.Integer, sa.ForeignKey("vendors.id", ondelete="SET NULL")), sa.Column("financial_year", sa.String(16), nullable=False), sa.Column("sanctioned_amount", sa.Numeric(16,2), nullable=False), sa.Column("actual_expenditure", sa.Numeric(16,2), nullable=False, server_default="0"), sa.Column("sanction_date", sa.DateTime(timezone=True), nullable=False), sa.Column("expected_completion_date", sa.DateTime(timezone=True), nullable=False), sa.Column("last_update_date", sa.DateTime(timezone=True), nullable=False), sa.Column("progress_percent", sa.Integer, nullable=False, server_default="0"), sa.Column("project_status", sa.String(24), nullable=False), sa.Column("source_checksum", sa.String(96)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("audit_runs", sa.Column("id", sa.Integer, primary_key=True), sa.Column("run_code", sa.String(72), nullable=False, unique=True), sa.Column("algorithm_version", sa.String(96), nullable=False), sa.Column("source_digest", sa.String(96), nullable=False), sa.Column("configuration", postgresql.JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")), sa.Column("total_projects", sa.Integer, nullable=False), sa.Column("total_alerts", sa.Integer, nullable=False, server_default="0"), sa.Column("status", sa.String(24), nullable=False), sa.Column("initiated_by_id", sa.Integer, sa.ForeignKey("users.id", ondelete="SET NULL")), sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("completed_at", sa.DateTime(timezone=True)))
    op.create_table("alerts", sa.Column("id", sa.Integer, primary_key=True), sa.Column("audit_run_id", sa.Integer, sa.ForeignKey("audit_runs.id", ondelete="CASCADE"), nullable=False), sa.Column("project_id", sa.Integer, sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False), sa.Column("risk_type", sa.String(64), nullable=False), sa.Column("risk_score", sa.Integer, nullable=False), sa.Column("risk_band", sa.String(24), nullable=False), sa.Column("alert_status", sa.String(32), nullable=False, server_default="open"), sa.Column("title", sa.String(255), nullable=False), sa.Column("rationale", sa.Text, nullable=False), sa.Column("evidence", postgresql.JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("review_actions", sa.Column("id", sa.Integer, primary_key=True), sa.Column("alert_id", sa.Integer, sa.ForeignKey("alerts.id", ondelete="CASCADE"), nullable=False), sa.Column("reviewer_id", sa.Integer, sa.ForeignKey("users.id", ondelete="RESTRICT"), nullable=False), sa.Column("action", sa.String(32), nullable=False), sa.Column("note", sa.Text, nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("model_runs", sa.Column("id", sa.Integer, primary_key=True), sa.Column("model_code", sa.String(96), nullable=False, unique=True), sa.Column("model_type", sa.String(96), nullable=False), sa.Column("version", sa.String(96), nullable=False), sa.Column("source_digest", sa.String(96), nullable=False), sa.Column("feature_schema", postgresql.JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")), sa.Column("evaluation", postgresql.JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")), sa.Column("artifact_key", sa.String(512)), sa.Column("limitation", sa.Text, nullable=False), sa.Column("trained_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    for table, column in [("users","email"),("vendors","vendor_code"),("projects","project_code"),("projects","category"),("projects","state"),("audit_runs","run_code"),("alerts","project_id"),("alerts","audit_run_id"),("review_actions","alert_id"),("model_runs","model_code")]: op.create_index(f"ix_{table}_{column}", table, [column])
def downgrade():
    for table in ["model_runs","review_actions","alerts","audit_runs","projects","vendors","users"]: op.drop_table(table)
